## Hey - your personal telegram notifier

Set simple reminders and texts with an easy, approachable CLI with notifications on all your devices

### Why

. Dead simple - all of 130 lines in a single script file
. No server process to run. Uses `st` daemon and most likely that's already running
. Telegram clients are available for pretty much every platform
But my machine isn't ONLINE 24x7::
. Install it on a server and with password-less ssh and setup a shell script or alias to execute `hey` on the server.

### Installation

[source,shell]
----
# clone the repo
# cd into the folder
sudo pip3 install -r requirements.txt

# check if at daemon is enabled & running
sudo systemctl status atd

# Enable and start it if needed.
sudo systemctl enable atd
sudo systemctl start atd

# link file hey.py as convenient
ln -sf /path/to/clone/hey.py ~/bin/hey

----

That's about it for installation
You'll need to configure a telegram bot 
before you can get started. See the section below

### Configuration

Create a telegram BOT::
. Create a telegram bot and send it a message
    * search for BotFather
    * type `/newbot`
    * give it a friendly name and a bot name (bot name must end in _bot)
    * Pick up the bot token from botfather.
. Get a chat id
    * Telegram global search, type your bot name or id
    * type `/start`
    * send any text.
    * Run `curl https://api.telegram.org/bot$TOKEN/getUpdates`
+
[source,shell]
----
    {
  "ok": true,
  "result": [
    {
      "update_id": 519260759,
      "message": {
        "message_id": 2,
        "from": {
          "id": 535955002,
          "is_bot": false,
        },
        "chat": {
          "id": 123456789, //<1> 
          "type": "private"
        },
        "date": 1567922393,
        "text": "hello"
      }
    }
  ]
}
----

. Update the `config` file in the folder with the bot token and chat id

### Config file locations

Files are read in the following sequence, later files override earlier entries defined in earlier ones.
. Alongside `hey.py`, named as `config`
. `/etc/hey.conf`
. `~/.config/hey.conf`

### Using it

[source,shell]
----

hey.py /t 10 AM Friday /m Get a hair cut

----

NOTE: arg parsing is basic and does not follow typical shell parsing conventions. 
First arg has to be `/t` and then it scans forward till a `/m`. The gathered string is 
parsed to a date. Anything after the /m is just concatenated to the message.

## Time expressions

[source,shell]
----
Time expression examples:
    in 10 minutes
    in 1 month
    next week
    friday 10 AM
    wed 10 AM
    10 AM Tues
Refer to https://dateparser.readthedocs.io/en/latest/ for documentation on date
expressions

----
